-- Commentum Shelby - Initial Schema
-- Simplified database design with JWT-based authentication

-- Mod Plus table - for role management (replaces env var role checking)
CREATE TABLE IF NOT EXISTS mod_plus (
  user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('moderator', 'admin', 'super_admin')),

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT mod_plus_pkey PRIMARY KEY (user_id)
);

-- Users table - minimal user information with centralized status tracking
CREATE TABLE IF NOT EXISTS users (
  user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN ('anilist', 'myanimelist', 'simkl', 'other')),

  -- User status (centralized - single source of truth)
  user_banned BOOLEAN DEFAULT FALSE,
  user_muted_until TIMESTAMPTZ,
  user_shadow_banned BOOLEAN DEFAULT FALSE,
  user_warnings INTEGER DEFAULT 0,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT users_pkey PRIMARY KEY (user_id, client_type),
  CONSTRAINT username_length CHECK (length(username) >= 1 AND length(username) <= 50)
);

-- Media table - store media information across all platforms
CREATE TABLE IF NOT EXISTS media (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  media_id TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN ('anilist', 'myanimelist', 'simkl', 'other')),
  media_type TEXT NOT NULL CHECK (media_type IN ('anime', 'manga', 'movie', 'tv', 'other')),
  title TEXT NOT NULL,
  year INTEGER,
  poster TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT media_unique UNIQUE (media_id, client_type),
  CONSTRAINT title_length CHECK (length(title) >= 1 AND length(title) <= 200)
);

-- Comments table - all comments across platforms
CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Core data
  user_id TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN ('anilist', 'myanimelist', 'simkl', 'other')),
  media_id TEXT NOT NULL,
  content TEXT NOT NULL,

  -- User information (cached from users table - minimal now)
  username TEXT NOT NULL,
  user_role TEXT DEFAULT 'user' CHECK (user_role IN ('user', 'moderator', 'admin', 'super_admin')),

  -- Media information (cached from media table)
  media_type TEXT NOT NULL CHECK (media_type IN ('anime', 'manga', 'movie', 'tv', 'other')),
  media_title TEXT NOT NULL,
  media_year INTEGER,
  media_poster TEXT,

  -- Comment structure
  parent_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,

  -- Comment states
  deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,

  pinned BOOLEAN DEFAULT FALSE,
  pinned_at TIMESTAMPTZ,
  pinned_by TEXT,

  locked BOOLEAN DEFAULT FALSE,
  locked_at TIMESTAMPTZ,
  locked_by TEXT,

  -- Edit tracking
  edited BOOLEAN DEFAULT FALSE,
  edited_at TIMESTAMPTZ,
  edit_count INTEGER DEFAULT 0,
  edit_history TEXT, -- JSON array

  -- Voting system
  upvotes INTEGER DEFAULT 0,
  downvotes INTEGER DEFAULT 0,
  vote_score INTEGER DEFAULT 0,
  user_votes TEXT, -- JSON object

  -- Reporting system
  reported BOOLEAN DEFAULT FALSE,
  report_count INTEGER DEFAULT 0,
  reports TEXT, -- JSON array
  report_status TEXT DEFAULT 'none' CHECK (report_status IN ('none', 'pending', 'reviewed', 'resolved', 'dismissed')),

  -- Content warnings
  tags TEXT, -- JSON array
  tagged_by TEXT,

  -- Moderation
  moderated BOOLEAN DEFAULT FALSE,
  moderated_at TIMESTAMPTZ,
  moderated_by TEXT,
  moderation_reason TEXT,
  moderation_action TEXT,

  -- System fields
  ip_address TEXT,
  user_agent TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT content_length CHECK (length(content) >= 1 AND length(content) <= 10000),
  CONSTRAINT username_length CHECK (length(username) >= 1 AND length(username) <= 50)
);

-- Discord integration tables
CREATE TABLE IF NOT EXISTS discord_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Discord user information
  discord_user_id TEXT UNIQUE NOT NULL,
  discord_username TEXT NOT NULL,
  discord_discriminator TEXT,
  discord_avatar TEXT,

  -- Platform mapping
  platform_user_id TEXT NOT NULL,
  platform_type TEXT NOT NULL CHECK (platform_type IN ('anilist', 'myanimelist', 'simkl', 'other')),

  -- Role and permissions
  user_role TEXT NOT NULL DEFAULT 'user' CHECK (user_role IN ('user', 'moderator', 'admin', 'super_admin')),

  -- Registration status
  is_verified BOOLEAN DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  registered_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE,

  -- Last activity
  last_command_at TIMESTAMPTZ,
  last_action_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS discord_notifications (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Notification type and target
  notification_type TEXT NOT NULL,
  target_id TEXT,
  target_type TEXT,

  -- Related data
  comment_data TEXT,
  user_data TEXT,
  media_data TEXT,

  -- Discord delivery info
  guild_id TEXT,
  channel_id TEXT,
  message_id TEXT,
  delivery_status TEXT DEFAULT 'pending',
  delivery_error TEXT,
  delivered_at TIMESTAMPTZ,

  -- Retry info
  retry_count INTEGER DEFAULT 0,
  next_retry_at TIMESTAMPTZ
);

-- Announcements system
CREATE TABLE IF NOT EXISTS announcements (
  id SERIAL PRIMARY KEY,

  -- App identification (for multi-app support)
  app_id VARCHAR(50) NOT NULL,

  -- Content
  title VARCHAR(200) NOT NULL,
  short_description VARCHAR(500) NOT NULL,
  full_content TEXT NOT NULL,

  -- Metadata
  author_id VARCHAR(100),
  author_name VARCHAR(100),

  -- Categorization
  category VARCHAR(50) DEFAULT 'general',
  priority INTEGER DEFAULT 0,

  -- Targeting
  target_roles TEXT[],
  target_platforms TEXT[],

  -- Status
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  pinned BOOLEAN DEFAULT FALSE,
  featured BOOLEAN DEFAULT FALSE,

  -- Timestamps
  published_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,

  -- Tracking
  view_count INTEGER DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT announcements_valid_status CHECK (status IN ('draft', 'published', 'archived'))
);

CREATE TABLE IF NOT EXISTS announcement_reads (
  id SERIAL PRIMARY KEY,
  announcement_id INTEGER REFERENCES announcements(id) ON DELETE CASCADE,
  user_id VARCHAR(100) NOT NULL,
  app_id VARCHAR(50) NOT NULL,
  read_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(announcement_id, user_id, app_id)
);

CREATE TABLE IF NOT EXISTS announcement_views (
  id SERIAL PRIMARY KEY,
  announcement_id INTEGER REFERENCES announcements(id) ON DELETE CASCADE,
  user_id VARCHAR(100),
  app_id VARCHAR(50) NOT NULL,
  viewed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_client_user ON users(client_type, user_id);
CREATE INDEX IF NOT EXISTS idx_media_client_media ON media(client_type, media_id);
CREATE INDEX IF NOT EXISTS idx_comments_client_user ON comments(client_type, user_id);
CREATE INDEX IF NOT EXISTS idx_comments_media ON comments(media_id, client_type);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_deleted ON comments(deleted);
CREATE INDEX IF NOT EXISTS idx_comments_role ON comments(user_role);
CREATE INDEX IF NOT EXISTS idx_comments_report_status ON comments(report_status);
CREATE INDEX IF NOT EXISTS idx_comments_pinned ON comments(pinned);
CREATE INDEX IF NOT EXISTS idx_comments_locked ON comments(locked);
CREATE INDEX IF NOT EXISTS idx_comments_vote_score ON comments(vote_score);

CREATE INDEX IF NOT EXISTS idx_discord_users_discord_id ON discord_users(discord_user_id);
CREATE INDEX IF NOT EXISTS idx_discord_users_platform ON discord_users(platform_type, platform_user_id);
CREATE INDEX IF NOT EXISTS idx_discord_users_role ON discord_users(user_role);
CREATE INDEX IF NOT EXISTS idx_discord_notifications_type ON discord_notifications(notification_type);
CREATE INDEX IF NOT EXISTS idx_discord_notifications_status ON discord_notifications(delivery_status);

CREATE INDEX IF NOT EXISTS idx_announcements_app_id ON announcements(app_id);
CREATE INDEX IF NOT EXISTS idx_announcements_status ON announcements(status);
CREATE INDEX IF NOT EXISTS idx_announcements_published_at ON announcements(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_app_status ON announcements(app_id, status);
CREATE INDEX IF NOT EXISTS idx_announcements_pinned ON announcements(pinned DESC, priority DESC, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_category ON announcements(app_id, category);
CREATE INDEX IF NOT EXISTS idx_announcement_reads_user ON announcement_reads(user_id, app_id);
CREATE INDEX IF NOT EXISTS idx_announcement_reads_announcement ON announcement_reads(announcement_id);
CREATE INDEX IF NOT EXISTS idx_announcement_views_announcement ON announcement_views(announcement_id);

-- Updated at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to tables
CREATE TRIGGER update_mod_plus_updated_at
  BEFORE UPDATE ON mod_plus
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_media_updated_at
  BEFORE UPDATE ON media
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_discord_users_updated_at
  BEFORE UPDATE ON discord_users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_announcements_updated_at
  BEFORE UPDATE ON announcements
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_comments_updated_at
  BEFORE UPDATE ON comments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Helper function to get comment depth using recursive CTE
CREATE OR REPLACE FUNCTION get_comment_depth(comment_id INTEGER)
RETURNS INTEGER AS $$
WITH RECURSIVE comment_tree AS (
  SELECT id, parent_id, 0 as depth
  FROM comments
  WHERE id = comment_id

  UNION ALL

  SELECT c.id, c.parent_id, ct.depth + 1
  FROM comments c
  INNER JOIN comment_tree ct ON c.id = ct.parent_id
)
SELECT MAX(depth) FROM comment_tree;
$$ LANGUAGE sql;
